import type { Metadata } from "next";
import './globals.css';

import { Geist, Geist_Mono } from 'next/font/google';

import { Toaster } from '@/components/ui/sonner';

import DarkMode from '../components/layout/DarkMode';

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="dark">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white dark:bg-black dark:text-primary-white text-black`}
            >
                <Toaster
                    richColors
                    duration={2000}
                    position="top-right"
                    closeButton={true}
                />

                {children}

                <DarkMode></DarkMode>
            </body>
        </html>
    );
}
