import type { Metadata } from "next";
import './globals.css';

import { Geist, Geist_Mono } from 'next/font/google';

import OfferComponent from '@/components/layout/OfferComponent';
import MobieSideBar from '@/components/layout/SideBar/MobieSideBar';
import SocketProvider from '@/components/layout/SocketProvider';
import { Toaster } from '@/components/ui/sonner';

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="dark">
            <head>
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"
                />
            </head>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white dark:bg-black dark:text-primary-white text-black`}
            >
                <Toaster
                    richColors
                    duration={2000}
                    position="top-right"
                    closeButton={true}
                />

                <SocketProvider>{children}</SocketProvider>
                {/* <DarkMode></DarkMode> */}
                <OfferComponent></OfferComponent>
                <MobieSideBar></MobieSideBar>
            </body>
        </html>
    );
}
